### ISSUE TITLE
can u add floating window/resize window just like native window manager.

### ISSUE THREAD

**Issue by spidy2356** [Ajay-056/Glaze-WM-Config#1]
I can't resize a window for specific app, it always opens like split mode. can u add that plz

**Comment by Ajay-056** [comment]
Have you tried the resize binding mode option (alt + c)?

**Comment by spidy2356** [comment]
edit: I take chris tech titus config from yt, but it gives error. I fix some error with the help of chat grp but still it give me some error. can u fix for me plz. here is the config.yaml

https://raw.githubusercontent.com/ChrisTitusTech/glazewm/main/config.yaml

**Comment by spidy2356** [comment]
> Have you tried the resize binding mode option (alt + c)?

yes, but it doesn't work for app overflow, it just add another panel besides and resize it

**Comment by Ajay-056** [comment]
> edit: I take chris tech titus config from yt, but it gives error. I fix some error with the help of chat grp but still it give me some error. can u fix for me plz. here is the config.yaml
> 
> https://raw.githubusercontent.com/ChrisTitusTech/glazewm/main/config.yaml

Please raise an issue in CTT's repo he can help you. Can you pls post some screenshots or logs to debug?
